#define DYNAMIC_KEYMAP_LAYER_COUNT 4
#define RGB_DI_PIN B0
#define RGBLED_NUM 2
#define RGBLED_SPLIT {1, 1}
#define SPLIT_USB_DETECT
#define SPLIT_LAYER_STATE_ENABLE
#define SPLIT_TRANSPORT_MIRROR
#define SPLIT_LED_STATE_ENABLE
#define RGB_DISABLE_WHEN_USB_SUSPENDED true
